name: Deploy

on:
  push:
    branches:
      - main  # or your default branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Run Ansible playbook
      uses: docker://ansible/ansible:ubuntu1804
      with:
        args: ansible-playbook -i inventory.ini deploy.yml
